services:
  go2rtc:
    image: alexxit/go2rtc:latest
    network_mode: host
    volumes:
      - ./go2rtc.yaml:/config/go2rtc.yaml
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:1984/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    devices:
      - /dev/dri:/dev/dri  # 挂载核显，如不需要转码H.254可以不用

  rtsp-pusher:
    build:
      context: ../..
      dockerfile: examples/rtsp/Dockerfile
    network_mode: host
    environment:
      - DEVICE_INDEX=${DEVICE_INDEX:-}
    volumes:
      - ../../data:/app/examples/rtsp/data
    depends_on:
      go2rtc:
        condition: service_healthy
    stdin_open: true
    tty: true
    restart: unless-stopped
